export const LoretteQuestions = [
  "Te souviens-tu de la première fois où tu as posé les yeux sur Lorette ?",
  "Quel est le dessin animé préféré de Lorette ?",
  "Quel est le souvenir le plus embarrassant que tu aies partagé avec Lorette ?",
  "Si Lorette devait un jour se reconvertir, quel métier choisirait-elle ?",
  "Parle-nous de ta première rencontre avec Lorette.",
  "Qu'as-tu pensé de Nicolas la première fois que tu l'as vu ?",
  "Que préfères-tu chez Lorette ?",
  "Si tu devais organiser un voyage avec Lorette, où l'emmènerais-tu ?",
  "Est-ce que tu trouves Lolo bonasse ?",
  "Si tu rencontrerais Lorette demain, quelle serait ta phrase d'accroche ?",
  "Si tu rencontrerais Lorette demain, deviendriez-vous amis ?",
  "En 30 secondes, envoie de l'amour à Lolo.",
  "Si tu pouvais dire une seule chose pour l'impressionner, que dirais-tu ?",
  "Quelle est la chanson préférée de Lorette ?",
  "Quel est le plus grand rêve de Lorette ?",
  "Si Lorette pouvait avoir un super-pouvoir, lequel choisirait-elle ?",
  "Quel est le plus grand défi que Lorette ait jamais relevé ?",
  "Quelle est la qualité la plus admirable chez Lorette selon toi ?",
  "Quel est l'endroit où Lorette se sent le plus paisible ?",
  "Si Lorette pouvait vivre à une époque historique, laquelle choisirait-elle ?",
  "Quelle est la meilleure blague que Lorette ait jamais racontée ?",
  "Quel est le livre préféré de Lorette ?",
  "Si Lorette devait être un animal, lequel serait-elle ?",
  "Quelle est la plus grande réussite de Lorette jusqu'à présent ?",
  "Quel est le talent le plus surprenant que possède Lorette ?",
  "Quelle est la boisson favorite de Lorette ?",
  "Quelle est la chose la plus folle que Lorette ait jamais faite ?",
  "Quel est le film préféré de Lorette et pourquoi ?",
  "Si Lorette pouvait changer une chose dans le monde, quelle serait-elle ?",
  "Quelle est la qualité la plus importante d'une amitié pour Lorette ?",
];

export const LouisQuestions = [
  "Quel est le surnom d'enfance de Louis ?",
  "Où Louis et Caroline se sont-ils rencontrés pour la première fois ?",
  "Quel est le plat préféré de Louis ?",
  "Quelle est la date exacte du premier rendez-vous de Louis et Caroline ?",
  "Quelle est la première chose que Louis a remarquée chez Caroline ?",
  "Quel est le film préféré de Louis ?",
  "Quel est le prénom du premier animal de compagnie de Louis ?",
  "Où Louis a-t-il proposé à Caroline ?",
  "Quel est le nom du premier concert auquel Louis a assisté ?",
  "Quel est le plus grand rêve de Louis en tant que mari ?",
  "Quel est le meilleur souvenir que vous ayez avec Louis ?",
  "Quelle est la qualité la plus marquante de Louis selon vous ?",
  "Si Louis était un super-héros, quel serait son super-pouvoir ?",
  "Quelle chanson ou musique représente le mieux Louis et pourquoi ?",
  "Quelle est la chose la plus folle que vous ayez vue Louis faire ?",
  "Si Louis était un animal, lequel serait-il et pourquoi ?",
  "Quel est le conseil le plus mémorable que Louis vous ait donné ?",
  "Quel est le rêve le plus fou que vous ayez entendu Louis exprimer ?",
  "Quelle est la première chose qui vous vient à l'esprit lorsque vous pensez à Louis ?",
  "Si Louis devait être célèbre pour quelque chose, quelle serait cette chose ?",
  "Quel est le talent secret de Louis dont peu de gens sont au courant ?",
  "Si Louis était un personnage de fiction, lequel serait-il et pourquoi ?",
  "Quelle est la blague ou le gag le plus mémorable que Louis ait jamais fait ?",
  "Quel est le lieu le plus inhabituel où vous avez vu Louis se retrouver ?",
  "Quelle est la meilleure qualité de Louis qui le rendrait parfait comme mari ?",
  "Quel est le plus grand défi que Louis ait jamais relevé ?",
  "Si Louis pouvait remonter dans le temps et changer une chose de son passé, que choisirait-il ?",
  "Quel est le moment le plus émouvant que vous ayez partagé avec Louis ?",
  "Si Louis devait être décrit en une seule phrase, quelle serait-elle ?",
  "Quelle est la chose la plus surprenante que vous ayez apprise sur Louis depuis qu'il est avec Caroline ?",
];

export const CommonQuestions = [
  "Chante-nous un petit truc",
  "Fais ta meilleure grimace",
  "Rote si t'es cap",
  "High Five ! (Self High Five si t'es seul)",
  "Rigole un coup",
  "Ta meilleure imitation",
  "Fais-nous l'accent marseillais",
  "Fais-nous l'accent asiatique",
  "Joue-nous la surprise",
  "Joue-nous la peur",
];
